export component Icon {
    in property <image> source;
    in property <color> color;
    in property <color> hover_color;
    in property <string> tooltip;

    callback clicked;

    width: 32px;
    height: 32px;

    touch := TouchArea {
        mouse-cursor: pointer;

        clicked => {
            root.clicked()
        }
    }

    Image {
        source: root.source;

        width: touch.has-hover ? parent.width + 2px : parent.width;
        height: touch.has-hover ? parent.height + 2px : parent.height;
        x: (parent.width - self.width) / 2;
        y: (parent.height - self.height) / 2;

        image-fit: contain;

        colorize: touch.has-hover
            ? root.hover_color
            : root.color;

        animate width { duration: 130ms; }
        animate height { duration: 130ms; }
    }

    if (touch.has-hover && root.tooltip != "") : Rectangle {
        x: parent.width + 8px;
        y: 0px;

        width: tooltip-text.preferred-width + 16px;
        height: 30px;

        background: #181818ee;
        border-radius: 6px;

        tooltip-text := Text {
            text: root.tooltip;
            color: white;

            x: 8px;
            y: 7px;
        }
    }
}
