import { Separator } from "separator.slint";
import { Icon } from "icon.slint";
import { Theme, Page } from "../theme.slint";

export component Sidebar inherits Rectangle {
    in property <image> account_head_image;

    width: 45px;
    height: 100%; // Default to full height, can be overridden

    border-color: Theme.accent_3;
    border-radius: 12px;
    border-width: 2px;
    background: Theme.accent_2;

    callback navigate(Page);

    Icon {
        source: @image-url("../../assets/logo.png");
        x: 7px;
        y: 12px;
        tooltip: "Vanta Launcher";
        clicked => {  }
    }

    Separator {
        separator_color: Theme.accent_3;
        width: parent.width - 24px;
        x: 12px;
        y: 56px;
    }

    Icon {
        source: @image-url("../../assets/icons/house.svg");
        color: Theme.accent_6;
        hover_color: Theme.accent_7;
        x: 10.5px;
        y: 68px;
        width: 24px;
        height: 24px;
        tooltip: "Home";
        clicked => { root.navigate(Page.Home) }
    }

    Icon {
        source: @image-url("../../assets/icons/library.svg");
        color: Theme.accent_6;
        hover_color: Theme.accent_7;
        x: 10.5px;
        y: 104px;
        width: 24px;
        height: 24px;
        tooltip: "Profiles";
        clicked => { root.navigate(Page.Library) }
    }

    Icon {
        source: @image-url("../../assets/icons/earth.svg");
        color: Theme.accent_6;
        hover_color: Theme.accent_7;
        x: 10.5px;
        y: 140px;
        width: 24px;
        height: 24px;
        tooltip: "Worlds";
        clicked => { root.navigate(Page.Worlds) }
    }

    Icon {
        source: @image-url("../../assets/icons/server.svg");
        color: Theme.accent_6;
        hover_color: Theme.accent_7;
        x: 10.5px;
        y: 176px;
        width: 24px;
        height: 24px;
        tooltip: "Servers";
        clicked => { root.navigate(Page.Servers) }
    }

    Separator {
        separator_color: Theme.accent_3;
        width: parent.width - 24px;
        x: 12px;
        y: 212px;
    }

    Icon {
        source: @image-url("../../assets/icons/modrinth.svg");
        color: Theme.accent_6;
        hover_color: Theme.accent_7;
        x: 10.5px;
        y: 224px;
        width: 24px;
        height: 24px;
        tooltip: "Modrinth";
        clicked => { root.navigate(Page.Modrinth) }
    }

    Icon {
        source: @image-url("../../assets/icons/curseforge.svg");
        color: Theme.accent_6;
        hover_color: Theme.accent_7;
        x: 10.5px;
        y: 260px;
        width: 24px;
        height: 24px;
        tooltip: "Curseforge";
        clicked => { root.navigate(Page.CurseForge) }
    }

    Separator {
        separator_color: Theme.accent_3;
        width: parent.width - 24px;
        x: 12px;
        y: parent.height - 96px;
    }

    Icon {
        source: @image-url("../../assets/icons/settings.svg");
        color: Theme.accent_6;
        hover_color: Theme.accent_7;
        x: 10.5px;
        y: parent.height - 84px;
        width: 24px;
        height: 24px;
        tooltip: "Settings";
        clicked => { root.navigate(Page.Settings) }
    }

    account-head-touch := TouchArea {
        x: 8.5px;
        y: parent.height - 44px;
        width: 28px;
        height: 28px;
        mouse-cursor: pointer;

        clicked => {
            root.navigate(Page.Accounts)
        }
    }

    Rectangle {
        x: account-head-touch.x;
        y: account-head-touch.y;
        width: account-head-touch.width;
        height: account-head-touch.height;

        border-color: Theme.accent_3;
        border-width: 2px;
        border-radius: 4px;
        clip: true;

        Image {
            source: root.account_head_image;
            image-fit: contain;
            width: account-head-touch.has-hover ? 26px : 24px;
            height: account-head-touch.has-hover ? 26px : 24px;
            x: (parent.width - self.width) / 2;
            y: (parent.height - self.height) / 2;

            animate width { duration: 130ms; }
            animate height { duration: 130ms; }
        }

        Rectangle {
            x: 0px;
            y: 0px;
            width: parent.width;
            height: parent.height;
            background: account-head-touch.has-hover ? #ffffff22 : #ffffff00;

            animate background { duration: 130ms; }
        }
    }

    if (account-head-touch.has-hover): Rectangle {
        x: account-head-touch.x + account-head-touch.width + 8px;
        y: account-head-touch.y - 1px;

        width: tooltip-text.preferred-width + 16px;
        height: 30px;

        background: #181818ee;
        border-radius: 6px;

        tooltip-text := Text {
            text: "Account";
            color: white;

            x: 8px;
            y: 7px;
        }
    }
}
