[package]
name = "vantalauncher"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
slint = "1.14.1"
directories = "5"
serde = { version = "1", features = ["derive"] }
toml = "0.8"
uuid = { version = "1.23.1", features = ["v3"] }
oauth2 = "5"
open = "5"
axum = "0.8"
tokio = { version = "1", features = ["full"] }
reqwest = { version = "0.12", features = ["json", "rustls-tls"] }
serde_json = "1"
keyring = "3"
minecraft-msa-auth = "0.4.0"
anyhow = "1.0.102"

[build-dependencies]
slint-build = "1.14.1"

[profile.release]
codegen-units = 1
lto = true
