import { Button, VerticalBox } from "std-widgets.slint";
import { Sidebar } from "components/sidebar.slint";

// Import Settings into Slint
export global Theme {
    in-out property <color> accent_1: #0a0a0a;
    in-out property <color> accent_2: #171717;
    in-out property <color> accent_3: #262626;
    in-out property <color> accent_4: #404040;
    in-out property <color> accent_5: #525252;
    in-out property <color> accent_6: #737373;
    in-out property <color> accent_7: #a3a3a3;
    in-out property <color> accent_8: #d4d4d4;
    in-out property <color> accent_9: #e5e5e5;
    in-out property <color> accent_10: #f5f5f5;
    in-out property <color> accent_11: #fafafa;
}

export component AppWindow inherits Window {
    background: Theme.accent_1;

    preferred-width: 1280px;
    preferred-height: 720px;
    min-width: 1000px;
    min-height: 600px;

    Sidebar {
        x: 20px;
        y: 20px;
        height: parent.height - 40px;
    }
}
