import { Button, VerticalBox } from "std-widgets.slint";
import { Sidebar } from "components/sidebar.slint";
import { Theme } from "theme.slint";

export { Theme }

export component AppWindow inherits Window {
    background: Theme.accent_1;

    preferred-width: 1280px;
    preferred-height: 720px;
    min-width: 1000px;
    min-height: 600px;

    Sidebar {
        x: 20px;
        y: 20px;
        height: parent.height - 40px;
    }
}
